# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/imports/xaui_0_example_design.xdc

# IP: ip/xaui_0/xaui_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xaui_0 || ORIG_REF_NAME==xaui_0} -quiet] -quiet
