# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/alexander.kohn/MYREPO2/axi_mac_xaui_GTP_synth/axi_mac_xaui_GTP_synth.srcs/constrs_1/imports/imports/xaui_0_example_design.xdc

# IP: /home/alexander.kohn/MYREPO2/axi_mac_xaui_GTP_synth/axi_mac_xaui_GTP_synth.srcs/sources_1/ip/xaui_0/xaui_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xaui_0 || ORIG_REF_NAME==xaui_0} -quiet] -quiet
